### ISSUE TITLE
Provide secrets

### ISSUE THREAD

**Issue by brmzkw** [koyeb/action-git-deploy#1]
Git deploy action accepts the parameter `service-env`, but we should also add a way to set and use secrets to store credentials.

**Comment by nilscox** [comment]
Not sure if it's documented, but the CLI accepts to set secrets with the syntax `--env KEY=@my-secret`

**Comment by brmzkw** [comment]
Nice! I didn't know.

In any case we need to add the secret creation in the action. It's not done yet.

**Comment by brmzkw** [comment]
Done, it is now possible to create a secret with:

```yaml
- name: Build and deploy the application to Koyeb
  uses: koyeb/action-git-deploy@v1
  with:
    [...]
    service-env: ENV_VAR=@MY_SECRET
```
