### ISSUE TITLE
Add support to configure healthchecks of instances being created/updated 

### ISSUE THREAD

**Issue by WalkingMist** [koyeb/action-git-deploy#10]
Currently, there are no facilities to configure healthchecks of the instance being created / updated via this GitHub Action and the default healthcheck grace period is too short that will fail a potential good deployment.

Maybe something like this will work:
````
- name: Build and deploy the application
  uses: koyeb/action-git-deploy@v1
  with:
   ...
    service-healthchecks:
    - port: 80
      protocol: "http"
      path: "/"
      method: "GET"
      is_public: true
      grace_period: 300
      interval: 30
      restart_limit: 3
      timeout: 600
    ...
````
